### ISSUE TITLE
How to change the Icon programmatically

### ISSUE THREAD

**Issue by ajimenezv** [MuhammadArsalanChishti/Cuboid-Circle-Button#1]
Hi! im not being able to change the icon of the button with the setCr_Icon(), im sending the id of the drawable to change but it doesnt.

**Comment by MuhammadArsalanChishti** [comment]
post code please!

**Comment by ColinWa** [comment]
CuboidButton cuboidBtn = (CuboidButton) gridViewAndroid.findViewById(R.id.cub_button);
cuboidBtn.setCr_icon(R.drawable.ic_person);

ERROR:

W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x412552a0)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at com.cuboid.cuboidcirclebutton.CuboidButton.scaleBitmap(CuboidButton.java:210)
                      at com.cuboid.cuboidcirclebutton.CuboidButton.imageIcon(CuboidButton.java:205)
                      at com.cuboid.cuboidcirclebutton.CuboidButton.onDraw(CuboidButton.java:132)
                      at android.view.View.draw(View.java:13776)
                      at android.view.View.getDisplayList(View.java:12727)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.widget.AbsListView.dispatchDraw(AbsListView.java:2631)
                      at android.view.View.draw(View.java:13779)
                      at android.widget.AbsListView.draw(AbsListView.java:4221)
                      at android.view.View.getDisplayList(View.java:12727)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.draw(View.java:13779)
                      at android.widget.FrameLayout.draw(FrameLayout.java:467)
                      at android.view.View.getDisplayList(View.java:12727)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.getDisplayList(View.java:12725)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.View.draw(View.java:13500)
                      at android.view.ViewGroup.drawChild(ViewGroup.java:3171)
                      at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3041)
                      at android.view.View.draw(View.java:13779)
                      at android.widget.FrameLayout.draw(FrameLayout.java:467)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2420)
                      at android.view.View.getDisplayList(View.java:12727)
                      at android.view.View.getDisplayList(View.java:12771)
                      at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
                      at android.view.ViewRootImpl.draw(ViewRootImpl.java:2278)
                      at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2150)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1961)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4526)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                      at android.view.Choreographer.doFrame(Choreographer.java:525)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                  	at andro

**Comment by ColinWa** [comment]
While awaiting feedback, in the meantime this might be useful:
Place your icon font in assets/fonts
Get it html entity characters n save in icons.xml in res


IN XML:

       <com.cuboid.cuboidcirclebutton.CuboidButton
              ...
              app:cub_fontstyle="fonts/your-icon-font.ttf"
              ...   
       />

IN CODE:

      cuboidBtn.setText(R.string.3dglasses)

**Comment by MuhammadArsalanChishti** [comment]
hello ColinWa font syle and icon both are different in my case for icon i am drawing it on canvas and for typeface it set given typeface

**Comment by MuhammadArsalanChishti** [comment]
hi ajimenezv
setCr_Icon() is now working fine
